#!/bin/bash
# This hook is run after this virtualenv is activated.

export PATH="/home/hogemin/.rbenv/bin:/home/hogemin/.rbenv/shims:${PATH}"
export RBENV_SHELL=bash
source '/home/hogemin/.rbenv/libexec/../completions/rbenv.bash'
rbenv rehash 2>/dev/null
rbenv() {
  local command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "`rbenv "sh-$command" "$@"`";;
  *)
    command rbenv "$command" "$@";;
  esac
}
export GEM_HOME=~/rb_sb/dev-snscrowler01/gems

export ORGDIR_BEFOREWO=`pwd`
cd ~/rb_sb/dev-snscrowler01

exit(){
  cd $ORGDIR_BEFOREWO
  deactivate
}
